spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: your_clientID_from_google_console
            clientSecret: your_clientSecret_from_google_console

            
