spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 542179580221-bsccmghe2kae2e3rs651lfak2vcfpb72.apps.googleusercontent.com
            clientSecret: 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